/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import TDA.Grafica;
import TDA.Questions;
import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.JDialog;

/**
 *
 * @author Lenovo
 */
public class Questionnaire extends javax.swing.JFrame {

    /**
     * Creates new form Questionnaire
     */
    Questions tda;
    Color selected = Color.decode("#828683");
    Color initial = new Color(200, 200, 200, 255);
    int a, b;
    
    public void establecer () {
        question.setText(tda.pregunta());
        picture.setIcon(tda.imagen());
        select.setSelectedIndex(tda.indice());
        number.setText(String.valueOf(select.getSelectedItem()));
        // Establecemos las Opciones
        String [] asignar = tda.establecer();
        // Ajustar para las sentencias de Verdadero/Falso
        jPanel2.removeAll();
        jPanel2.add(option1);
        jPanel2.add(option2);
        jPanel2.add(option3);
        jPanel2.add(option4);
        if (tda.indice() == tda.vF1 || tda.indice() == tda.vF2) {
            option1.setText(asignar[0]);
            option2.setText(asignar[1]);
            option3.setText(asignar[2]);
            option4.setText(asignar[3]);
            if (option1.getText().isEmpty())
                jPanel2.remove(option1);
            if (option2.getText().isEmpty())
                jPanel2.remove(option2);
            if (option3.getText().isEmpty())
                jPanel2.remove(option3);
            if (option4.getText().isEmpty())
                jPanel2.remove(option4);
        } else {
            option1.setText(asignar[0]);
            option2.setText(asignar[1]);
            option3.setText(asignar[2]);
            option4.setText(asignar[3]);
        }
        
        // Condiciones Para los Botones
        previous.setEnabled(tda.indice() != 0);
        if (tda.indice() == 9)
            next.setText("Finalizar");
        else
            next.setText("Siguiente");
        
        // Checar si ya se ha respondido algo
        responder();
    }
    
    public void responder () {
        if (!tda.contestado[tda.indice()].isEmpty()) {
            if (option1.getText().contains(tda.contestado[tda.indice()]))
            option1.setBackground(selected);
            else option1.setBackground(initial);

            if (option2.getText().contains(tda.contestado[tda.indice()]))
                option2.setBackground(selected);
            else option2.setBackground(initial);

            if (option3.getText().contains(tda.contestado[tda.indice()]))
                option3.setBackground(selected);
            else option3.setBackground(initial);

            if (option4.getText().contains(tda.contestado[tda.indice()]))
                option4.setBackground(selected);
            else option4.setBackground(initial);
        } else {
            option1.setBackground(initial);
            option2.setBackground(initial);
            option3.setBackground(initial);
            option4.setBackground(initial);
        }
    }
    
    public void evaluar () {
        int correct = tda.evaluar();
        Grafica.crearGrafica(Grafica.datos(correct));
    }
    
    public Questionnaire() {
        initComponents();
        tda = new Questions(picture);
        establecer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        number = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        picture = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        option1 = new javax.swing.JButton();
        option2 = new javax.swing.JButton();
        option3 = new javax.swing.JButton();
        option4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        previous = new javax.swing.JButton();
        select = new javax.swing.JComboBox<>();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUESTIONARIO: Graphics");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        number.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        number.setText("Pregunta 00");
        number.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        number.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        question.setEditable(false);
        question.setColumns(1);
        question.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        question.setLineWrap(true);
        question.setRows(1);
        question.setTabSize(1);
        question.setText("Pregunta va aqui XD");
        question.setWrapStyleWord(true);
        jScrollPane2.setViewportView(question);

        picture.setText("Imagen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 15, 15));

        option1.setText("Opcion 1");
        option1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                option1MouseClicked(evt);
            }
        });
        jPanel2.add(option1);

        option2.setText("Opcion 2");
        option2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                option2MouseClicked(evt);
            }
        });
        jPanel2.add(option2);

        option3.setText("Opcion 3");
        option3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                option3MouseClicked(evt);
            }
        });
        jPanel2.add(option3);

        option4.setText("Opcion 4");
        option4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                option4MouseClicked(evt);
            }
        });
        jPanel2.add(option4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 15, 0));

        previous.setText("Anterior");
        previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousMouseClicked(evt);
            }
        });
        jPanel3.add(previous);

        String [] indice = new String [10];
        for (int i = 1; i <= indice.length; i++)
        indice[i-1] = "Pregunta " + i;
        select.setModel(new javax.swing.DefaultComboBoxModel<>(indice));
        select.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectItemStateChanged(evt);
            }
        });
        jPanel3.add(select);

        next.setText("Siguiente");
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        jPanel3.add(next);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        // TODO add your handling code here:
        if (next.getText().contains("Siguiente")) {
            tda.next();
            establecer();
        } else {
            evaluar();
            Finish.main(null);
            setVisible(false);
        }
    }//GEN-LAST:event_nextMouseClicked

    private void selectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            tda.select(select.getSelectedIndex());
            establecer();
        }
    }//GEN-LAST:event_selectItemStateChanged

    private void previousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMouseClicked
        // TODO add your handling code here:
        if (previous.isEnabled()) {
            tda.previous();
            establecer();
        }
    }//GEN-LAST:event_previousMouseClicked

    private void option1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option1MouseClicked
        // TODO add your handling code here:
        if (option1.isEnabled()) {
            tda.contestado[tda.indice()] = option1.getText();
            responder();
        }
    }//GEN-LAST:event_option1MouseClicked

    private void option2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option2MouseClicked
        // TODO add your handling code here:
        if (option2.isEnabled()) {
            tda.contestado[tda.indice()] = option2.getText();
            responder();
        }
    }//GEN-LAST:event_option2MouseClicked

    private void option3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option3MouseClicked
        // TODO add your handling code here:
        if (option3.isEnabled()) {
            tda.contestado[tda.indice()] = option3.getText();
            responder();
        }
    }//GEN-LAST:event_option3MouseClicked

    private void option4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option4MouseClicked
        // TODO add your handling code here:
        if (option4.isEnabled()) {
            tda.contestado[tda.indice()] = option4.getText();
            responder();
        }
    }//GEN-LAST:event_option4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questionnaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questionnaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton next;
    private javax.swing.JLabel number;
    private javax.swing.JButton option1;
    private javax.swing.JButton option2;
    private javax.swing.JButton option3;
    private javax.swing.JButton option4;
    private javax.swing.JLabel picture;
    private javax.swing.JButton previous;
    private javax.swing.JTextArea question;
    private javax.swing.JComboBox<String> select;
    // End of variables declaration//GEN-END:variables
}
